name: Lint Code Base for Challenge

# Start the job on all push #

on:
  push:
    # Remove the line above to run when pushing to master
    branches-ignore: [master]
  pull_request:
    branches: [master]

# Set the Job #

jobs:
  build:
    # Name the Job
    name: Lint Code Base for Challenge
    # Set the agent to run on
    runs-on: ubuntu-latest

    # Load all steps #

    steps:

      # Checkout the code base #

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

       # Run Linter against code base #

      - name: Lint Code Base for Challenge
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Terrascan will complain about 22 port open to the Internet and S3 bucket with no access policy.
          # This is just a test, we'll disable it this time.
          VALIDATE_TERRAFORM_TERRASCAN: false
          # TODO: Execute golangci-lint direcly in the next step
          VALIDATE_GO: false